FROM centos:centos6
MAINTAINER Genki Sugawara <sgwr_dts@yahoo.co.jp>

USER root
WORKDIR /

RUN yum install -y rpmdevtools
RUN rpmdev-setuptree

RUN yum install -y make

ENV GO_VERSION 1.7
ENV GOROOT=/usr/local/go
ENV GOPATH=/root/.go
RUN wget -q https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz
RUN tar xf go*.linux-amd64.tar.gz
RUN mv go /usr/local/
RUN rm go*.linux-amd64.tar.gz
RUN mkdir $GOPATH
